INSERT INTO niveaux (nom, description, points) VALUES
  ('Débutant', 'Niveau de base', 0),
  ('Intermédiaire', 'Quelques points acquis', 100),
  ('Avancé', 'Bon niveau', 250),
  ('Expert', 'Très bon niveau', 500),
  ('Maître', 'Niveau ultime', 1000);

INSERT INTO avatars (nom, image, id_utilisateur) VALUES
  ('Héros', 'hero.png', 1),
  ('Mage', 'mage.png', 2),
  ('Guerrier', 'warrior.png', 3),
  ('Archer', 'archer.png', 4),
  ('Paladin', 'paladin.png', 5),
  ('Ninja', 'ninja.png', 6),
  ('Samouraï', 'samurai.png', 7),
  ('Druide', 'druid.png', 8),
  ('Nécromancien', 'necromancer.png', 9),
  ('Sorcier', 'sorcerer.png', 10),
  ('Barde', 'bard.png', 11),
  ('Voleur', 'thief.png', 12),
  ('Assassin', 'assassin.png', 13),
  ('Chevalier', 'knight.png', 14),
  ('Viking', 'viking.png', 15),
  ('Spartiate', 'spartan.png', 16),
  ('Gladiateur', 'gladiator.png', 17),
  ('Moine', 'monk.png', 18),
  ('Alchimiste', 'alchemist.png', 19),
  ('Ingénieur', 'engineer.png', 20),
  ('Artificier', 'artificer.png', 21),
  ('Ranger', 'ranger.png', 22),
  ('Chasseur', 'hunter.png', 23),
  ('Mercenaire', 'mercenary.png', 24),
  ('Pirate', 'pirate.png', 25);

INSERT INTO avatars_versions (surnom, level, id_avatar, id_niveau) VALUES
  ('Le Brave', 1, 1, 1),
  ('Le Sage', 2, 2, 2),
  ('Le Protecteur', 5, 3, 5),
  ('L''Œil de Faucon', 3, 4, 3),
  ('Le Juste', 4, 5, 4),
  ('L''Ombre', 5, 6, 5),
  ('L''Honorable', 4, 7, 4),
  ('Le Gardien de la Nature', 3, 8, 3),
  ('Le Sombre', 5, 9, 5),
  ('L''Élémental', 4, 10, 4),
  ('Le Chanteur', 2, 11, 2),
  ('Le Furtif', 3, 12, 3),
  ('Le Tueur Silencieux', 5, 13, 5),
  ('Le Noble', 4, 14, 4),
  ('Le Conquérant', 5, 15, 5),
  ('Le Guerrier Légendaire', 5, 16, 5),
  ('Le Champion', 4, 17, 4),
  ('Le Zen', 3, 18, 3),
  ('Le Savant', 2, 19, 2),
  ('Le Bricoleur', 2, 20, 2),
  ('Le Créatif', 3, 21, 3),
  ('Le Traqueur', 3, 22, 3),
  ('Le Pisteur', 2, 23, 2),
  ('Le Sans-Loi', 1, 24, 1),
  ('Le Corsaire', 4, 25, 4);
